#!/usr/bin/env bash
# Build the SAPMAP-vendored Dirty Frag binary and inject the bytes
# into modules/exploitation/_dirtyfrag_blob.py.
#
# Run on any Linux x86_64 host (or via `docker run --rm -v $PWD:/src ...`)
# — the resulting blob ships with SAPMAP, so this is a one-off step.
#
# Usage:
#   bash tools/dirtyfrag/build.sh                # use local gcc
#   DOCKER=1 bash tools/dirtyfrag/build.sh       # build inside an alpine container
#
# Required on the build host:
#   - gcc (or clang) with static-libc support (alpine: apk add gcc musl-dev)
#   - python3 (any 3.x) for blob injection
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SRC="$HERE/exp.c"
OUT="$HERE/df_static"
BLOB_PY="$ROOT/modules/exploitation/_dirtyfrag_blob.py"

if [ ! -f "$SRC" ]; then
    echo "ERROR: $SRC not found.  Run from a checkout of SAPMAP." >&2
    exit 1
fi

if [ "${DOCKER:-0}" = "1" ]; then
    echo "[*] Building inside alpine via docker..."
    docker run --rm \
        -v "$HERE:/work" \
        -w /work \
        alpine:3.20 sh -c '
            apk add --no-cache gcc musl-dev linux-headers >/dev/null
            gcc -O2 -static -Wall -o df_static exp.c
            strip df_static
            ls -la df_static
        '
else
    if ! command -v gcc >/dev/null 2>&1; then
        echo "ERROR: gcc not found.  Install gcc + static libc (e.g. on alpine: apk add gcc musl-dev linux-headers), or re-run with DOCKER=1." >&2
        exit 1
    fi
    UNAME_S="$(uname -s)"
    if [ "$UNAME_S" != "Linux" ]; then
        echo "ERROR: This build script must run on Linux (uname -s = $UNAME_S)." >&2
        echo "       Re-run with DOCKER=1 to build via container, or scp tools/dirtyfrag/ to a Linux host." >&2
        exit 1
    fi
    UNAME_M="$(uname -m)"
    if [ "$UNAME_M" != "x86_64" ]; then
        echo "ERROR: x86_64 build host required (uname -m = $UNAME_M)." >&2
        exit 1
    fi
    echo "[*] Building with local gcc..."
    cd "$HERE"
    gcc -O2 -static -Wall -o df_static exp.c
    strip df_static
    ls -la df_static
fi

if [ ! -f "$OUT" ]; then
    echo "ERROR: build did not produce $OUT" >&2
    exit 1
fi

SIZE="$(wc -c < "$OUT" | tr -d ' ')"
echo "[+] df_static built: $SIZE bytes"

echo "[*] Injecting binary into $BLOB_PY ..."
python3 - <<PY
import os, sys, hashlib
path = "$OUT"
with open(path, "rb") as f:
    data = f.read()
sha = hashlib.sha256(data).hexdigest()
hexstr = data.hex()
# 80 hex chars per line (40 bytes per line in source)
lines = [hexstr[i:i+80] for i in range(0, len(hexstr), 80)]
body = '\n'.join(f'    "{ln}"' for ln in lines)
out_py = '''"""Auto-generated by tools/dirtyfrag/build.sh — do not hand-edit.

Holds the SAPMAP-vendored Dirty Frag binary as a hex blob.  The blob is
delivered to the target via SAPXPG, hex-decoded into /tmp/.df_bin, then
chmod +x'd and run.  See modules/exploitation/sapmap_dirtyfrag.py.
"""

DIRTYFRAG_SHA256 = "{sha}"
DIRTYFRAG_SIZE   = {size}

DIRTYFRAG_BIN_HEX = (
{body}
)
'''.format(sha=sha, size=len(data), body=body)
with open("$BLOB_PY", "w") as f:
    f.write(out_py)
print(f"[+] Wrote {len(data)} bytes ({len(hexstr)} hex chars) to {os.path.basename('$BLOB_PY')}")
print(f"[+] sha256: {sha}")
PY

echo "[+] Done.  modules/exploitation/_dirtyfrag_blob.py is ready."
echo "    SAPMAP will pick it up on next launch."
